/* Generated By:JJTree: Do not edit this line. ASTArguments.java */

package com.tinyplanet.javaparser;

public class ASTArguments extends SimpleNode {
  public ASTArguments(int id) {
    super(id);
  }

  public ASTArguments(JavaParser p, int id) {
    super(p, id);
  }

}
