/* Generated By:JJTree: Do not edit this line. ASTArgumentList.java */

package com.tinyplanet.javaparser;

public class ASTArgumentList extends SimpleNode {
  public ASTArgumentList(int id) {
    super(id);
  }

  public ASTArgumentList(JavaParser p, int id) {
    super(p, id);
  }

}
