/* Generated By:JJTree: Do not edit this line. ASTContinueStatement.java */

package com.tinyplanet.javaparser;

public class ASTContinueStatement extends SimpleNode {
  public ASTContinueStatement(int id) {
    super(id);
  }

  public ASTContinueStatement(JavaParser p, int id) {
    super(p, id);
  }

}
