/* Generated By:JJTree: Do not edit this line. ASTClassBodyDeclaration.java */

package com.tinyplanet.javaparser;

public class ASTClassBodyDeclaration extends SimpleNode {
  public ASTClassBodyDeclaration(int id) {
    super(id);
  }

  public ASTClassBodyDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
