/* Generated By:JJTree: Do not edit this line. ASTClassDeclaration.java */

package com.tinyplanet.javaparser;

public class ASTClassDeclaration extends SimpleNode {
  public ASTClassDeclaration(int id) {
    super(id);
  }

  public ASTClassDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
