/* Generated By:JJTree: Do not edit this line. ASTDoStatement.java */

package com.tinyplanet.javaparser;

public class ASTDoStatement extends SimpleNode {
  public ASTDoStatement(int id) {
    super(id);
  }

  public ASTDoStatement(JavaParser p, int id) {
    super(p, id);
  }

}
