/* Generated By:JJTree: Do not edit this line. ASTExpression.java */

package com.tinyplanet.javaparser;

public class ASTExpression extends SimpleNode {
  public ASTExpression(int id) {
    super(id);
  }

  public ASTExpression(JavaParser p, int id) {
    super(p, id);
  }

}
