/* Generated By:JJTree: Do not edit this line. ASTFormalParameters.java */

package com.tinyplanet.javaparser;

public class ASTFormalParameters extends SimpleNode {
  public ASTFormalParameters(int id) {
    super(id);
  }

  public ASTFormalParameters(JavaParser p, int id) {
    super(p, id);
  }

}
