/* Generated By:JJTree: Do not edit this line. ASTInterfaceDeclaration.java */

package com.tinyplanet.javaparser;

public class ASTInterfaceDeclaration extends SimpleNode {
  public ASTInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTInterfaceDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
