/* Generated By:JJTree: Do not edit this line. ASTImportDeclaration.java */

package com.tinyplanet.javaparser;

public class ASTImportDeclaration extends SimpleNode {
  public ASTImportDeclaration(int id) {
    super(id);
  }

  public ASTImportDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
