/* Generated By:JJTree: Do not edit this line. ASTIfStatement.java */

package com.tinyplanet.javaparser;

public class ASTIfStatement extends SimpleNode {
  public ASTIfStatement(int id) {
    super(id);
  }

  public ASTIfStatement(JavaParser p, int id) {
    super(p, id);
  }

}
