/* Generated By:JJTree: Do not edit this line. ASTInclusiveOrExpression.java */

package com.tinyplanet.javaparser;

public class ASTInclusiveOrExpression extends SimpleNode {
  public ASTInclusiveOrExpression(int id) {
    super(id);
  }

  public ASTInclusiveOrExpression(JavaParser p, int id) {
    super(p, id);
  }

}
