/* Generated By:JJTree: Do not edit this line. ASTLocalVariableDeclaration.java */

package com.tinyplanet.javaparser;

public class ASTLocalVariableDeclaration extends SimpleNode {
  public ASTLocalVariableDeclaration(int id) {
    super(id);
  }

  public ASTLocalVariableDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
