/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarator.java */

package com.tinyplanet.javaparser;

public class ASTMethodDeclarator extends SimpleNode {
  public ASTMethodDeclarator(int id) {
    super(id);
  }

  public ASTMethodDeclarator(JavaParser p, int id) {
    super(p, id);
  }

}
