/* Generated By:JJTree: Do not edit this line. ASTMethodDeclarationLookahead.java */

package com.tinyplanet.javaparser;

public class ASTMethodDeclarationLookahead extends SimpleNode {
  public ASTMethodDeclarationLookahead(int id) {
    super(id);
  }

  public ASTMethodDeclarationLookahead(JavaParser p, int id) {
    super(p, id);
  }

}
