/* Generated By:JJTree: Do not edit this line. ASTNestedClassDeclaration.java */

package com.tinyplanet.javaparser;

public class ASTNestedClassDeclaration extends SimpleNode {
  public ASTNestedClassDeclaration(int id) {
    super(id);
  }

  public ASTNestedClassDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
