/* Generated By:JJTree: Do not edit this line. ASTName.java */

package com.tinyplanet.javaparser;

public class ASTName extends SimpleNode {
  public ASTName(int id) {
    super(id);
  }

  public ASTName(JavaParser p, int id) {
    super(p, id);
  }

}
