/* Generated By:JJTree: Do not edit this line. ASTNestedInterfaceDeclaration.java */

package com.tinyplanet.javaparser;

public class ASTNestedInterfaceDeclaration extends SimpleNode {
  public ASTNestedInterfaceDeclaration(int id) {
    super(id);
  }

  public ASTNestedInterfaceDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
