/* Generated By:JJTree: Do not edit this line. ASTNullLiteral.java */

package com.tinyplanet.javaparser;

public class ASTNullLiteral extends SimpleNode {
  public ASTNullLiteral(int id) {
    super(id);
  }

  public ASTNullLiteral(JavaParser p, int id) {
    super(p, id);
  }

}
