/* Generated By:JJTree: Do not edit this line. ASTPostfixExpression.java */

package com.tinyplanet.javaparser;

public class ASTPostfixExpression extends SimpleNode {
  public ASTPostfixExpression(int id) {
    super(id);
  }

  public ASTPostfixExpression(JavaParser p, int id) {
    super(p, id);
  }

}
