/* Generated By:JJTree: Do not edit this line. ASTPackageDeclaration.java */

package com.tinyplanet.javaparser;

public class ASTPackageDeclaration extends SimpleNode {
  public ASTPackageDeclaration(int id) {
    super(id);
  }

  public ASTPackageDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
