/* Generated By:JJTree: Do not edit this line. ASTPrimarySuffix.java */

package com.tinyplanet.javaparser;

public class ASTPrimarySuffix extends SimpleNode {
  public ASTPrimarySuffix(int id) {
    super(id);
  }

  public ASTPrimarySuffix(JavaParser p, int id) {
    super(p, id);
  }

}
