/* Generated By:JJTree: Do not edit this line. ASTPrimitiveType.java */

package com.tinyplanet.javaparser;

public class ASTPrimitiveType extends SimpleNode {
  public ASTPrimitiveType(int id) {
    super(id);
  }

  public ASTPrimitiveType(JavaParser p, int id) {
    super(p, id);
  }

}
