/* Generated By:JJTree: Do not edit this line. ASTResultType.java */

package com.tinyplanet.javaparser;

public class ASTResultType extends SimpleNode {
  public ASTResultType(int id) {
    super(id);
  }

  public ASTResultType(JavaParser p, int id) {
    super(p, id);
  }

}
