/* Generated By:JJTree: Do not edit this line. ASTSynchronizedStatement.java */

package com.tinyplanet.javaparser;

public class ASTSynchronizedStatement extends SimpleNode {
  public ASTSynchronizedStatement(int id) {
    super(id);
  }

  public ASTSynchronizedStatement(JavaParser p, int id) {
    super(p, id);
  }

}
