/* Generated By:JJTree: Do not edit this line. ASTStatementExpressionList.java */

package com.tinyplanet.javaparser;

public class ASTStatementExpressionList extends SimpleNode {
  public ASTStatementExpressionList(int id) {
    super(id);
  }

  public ASTStatementExpressionList(JavaParser p, int id) {
    super(p, id);
  }

}
