/* Generated By:JJTree: Do not edit this line. ASTSwitchLabel.java */

package com.tinyplanet.javaparser;

public class ASTSwitchLabel extends SimpleNode {
  public ASTSwitchLabel(int id) {
    super(id);
  }

  public ASTSwitchLabel(JavaParser p, int id) {
    super(p, id);
  }

}
