/* Generated By:JJTree: Do not edit this line. ASTSwitchStatement.java */

package com.tinyplanet.javaparser;

public class ASTSwitchStatement extends SimpleNode {
  public ASTSwitchStatement(int id) {
    super(id);
  }

  public ASTSwitchStatement(JavaParser p, int id) {
    super(p, id);
  }

}
