/* Generated By:JJTree: Do not edit this line. ASTType.java */

package com.tinyplanet.javaparser;

public class ASTType extends SimpleNode {
  public ASTType(int id) {
    super(id);
  }

  public ASTType(JavaParser p, int id) {
    super(p, id);
  }

}
