/* Generated By:JJTree: Do not edit this line. ASTUnmodifiedClassDeclaration.java */

package com.tinyplanet.javaparser;

public class ASTUnmodifiedClassDeclaration extends SimpleNode {
  public ASTUnmodifiedClassDeclaration(int id) {
    super(id);
  }

  public ASTUnmodifiedClassDeclaration(JavaParser p, int id) {
    super(p, id);
  }

}
