/* Generated By:JJTree: Do not edit this line. ASTVariableDeclaratorId.java */

package com.tinyplanet.javaparser;

public class ASTVariableDeclaratorId extends SimpleNode {
  public ASTVariableDeclaratorId(int id) {
    super(id);
  }

  public ASTVariableDeclaratorId(JavaParser p, int id) {
    super(p, id);
  }

}
